import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Clear existing data
  await prisma.review.deleteMany()
  await prisma.booking.deleteMany()
  await prisma.listing.deleteMany()

  const listings = [
    {
      slug: 'luxury-penthouse-fifth-settlement',
      title: 'Luxury Penthouse in Fifth Settlement',
      titleAr: 'بنتهاوس فاخر في التجمع الخامس',
      description: 'Stunning 3-bedroom penthouse with panoramic city views, private rooftop terrace, and premium finishes throughout. Located in the heart of Fifth Settlement with easy access to Waterway and City Stars.',
      descriptionAr: 'بنتهاوس مذهل من 3 غرف نوم مع إطلالات بانورامية على المدينة، تراس خاص على السطح، وتشطيبات فاخرة في جميع أنحاء المكان.',
      location: 'Fifth Settlement',
      area: 'New Cairo',
      city: 'Cairo',
      pricePerNight: 2500,
      utilitiesEst: 200,
      cleaningFee: 500,
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 6,
      amenities: ['Pool', 'Gym', 'Parking', 'Workspace', 'WiFi', 'AC', 'Kitchen', 'Washer', 'Balcony', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      ],
      rating: 4.8,
      reviewCount: 24,
      refundPolicy: 'flexible',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 3 * 60 * 60 * 1000),
      viewCount: 142,
      latitude: 30.0075,
      longitude: 31.4367,
    },
    {
      slug: 'modern-apartment-katameya',
      title: 'Modern 2BR in Katameya Heights',
      titleAr: 'شقة عصرية 2 غرفة في كتامييا هايتس',
      description: 'Beautiful 2-bedroom apartment in the prestigious Katameya Heights compound. Features contemporary design, fully equipped kitchen, and access to compound amenities including pool, gym, and tennis courts.',
      descriptionAr: 'شقة جميلة من غرفتين في كمبوند كتامييا هايتس المرموق. تتميز بتصميم عصري ومطبخ مجهز بالكامل.',
      location: 'Katameya',
      area: 'New Cairo',
      city: 'Cairo',
      pricePerNight: 1800,
      utilitiesEst: 150,
      cleaningFee: 350,
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      amenities: ['Pool', 'Gym', 'Tennis Court', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Washer', 'Security', 'Playground'],
      images: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
      ],
      rating: 4.6,
      reviewCount: 18,
      refundPolicy: 'moderate',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 6 * 60 * 60 * 1000),
      viewCount: 98,
      latitude: 30.0200,
      longitude: 31.4500,
    },
    {
      slug: 'cozy-studio-new-cairo',
      title: 'Cozy Studio Near AUC',
      titleAr: 'استوديو مريح بالقرب من الجامعة الأمريكية',
      description: 'Perfect solo or couple getaway — bright studio with smart storage, high-speed WiFi, and walking distance to AUC campus and Cairo Festival City mall.',
      descriptionAr: 'مثالي للأزواج أو المسافرين المنفردين — استوديو مضيء مع تخزين ذكي، إنترنت فائق السرعة، على مسافة قريبة من الجامعة الأمريكية.',
      location: 'New Cairo City',
      area: 'New Cairo',
      city: 'Cairo',
      pricePerNight: 900,
      utilitiesEst: 80,
      cleaningFee: 200,
      bedrooms: 0,
      bathrooms: 1,
      maxGuests: 2,
      amenities: ['WiFi', 'AC', 'Kitchen', 'Washer', 'Workspace', 'Smart TV', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      ],
      rating: 4.5,
      reviewCount: 31,
      refundPolicy: 'flexible',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 2 * 60 * 60 * 1000),
      viewCount: 210,
      latitude: 30.0333,
      longitude: 31.4600,
    },
    {
      slug: 'family-villa-shorouk',
      title: 'Spacious Family Villa in Shorouk',
      titleAr: 'فيلا عائلية فسيحة في الشروق',
      description: 'Large 4-bedroom villa with private garden, BBQ area, and dedicated parking. Perfect for family holidays with ample space for children. Located in the quiet and leafy Shorouk City.',
      descriptionAr: 'فيلا كبيرة من 4 غرف نوم مع حديقة خاصة، منطقة شواء، وموقف سيارات مخصص. مثالية للعطلات العائلية.',
      location: 'Shorouk City',
      area: 'New Cairo',
      city: 'Cairo',
      pricePerNight: 3200,
      utilitiesEst: 300,
      cleaningFee: 700,
      bedrooms: 4,
      bathrooms: 3,
      maxGuests: 10,
      amenities: ['Garden', 'BBQ', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Washer', 'Security', 'Kids Play Area', 'Smart TV'],
      images: [
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      ],
      rating: 4.9,
      reviewCount: 12,
      refundPolicy: 'moderate',
      eligibility: 'families',
      isActive: true,
      lastBooked: new Date(Date.now() - 24 * 60 * 60 * 1000),
      viewCount: 67,
      latitude: 30.1200,
      longitude: 31.6100,
    },
    {
      slug: 'beachfront-chalet-marassi',
      title: 'Beachfront Chalet at Marassi',
      titleAr: 'شاليه على الشاطئ في مراسي',
      description: 'Wake up to the Mediterranean Sea in this stunning 2-bedroom beachfront chalet at Marassi. Direct beach access, resort-style pools, and all Marassi amenities at your doorstep.',
      descriptionAr: 'استيقظ على منظر البحر الأبيض المتوسط في هذا الشاليه المذهل على الشاطئ في مراسي. وصول مباشر للشاطئ وحمامات سباحة فندقية.',
      location: 'Marassi',
      area: 'North Coast',
      city: 'North Coast',
      pricePerNight: 3500,
      utilitiesEst: 0,
      cleaningFee: 600,
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 5,
      amenities: ['Beach Access', 'Pool', 'Gym', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Marina', 'Restaurants', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
      ],
      rating: 4.9,
      reviewCount: 47,
      refundPolicy: 'non-refundable',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 1 * 60 * 60 * 1000),
      viewCount: 389,
      latitude: 30.8700,
      longitude: 28.7500,
    },
    {
      slug: 'fouka-bay-chalet',
      title: 'Luxury Chalet at Fouka Bay',
      titleAr: 'شاليه فاخر في فوكا باي',
      description: 'Exquisite 3-bedroom chalet in the award-winning Fouka Bay development. Private pool, sea views, and access to one of the North Coast\'s finest beach resorts.',
      descriptionAr: 'شاليه فاخر من 3 غرف نوم في مشروع فوكا باي الحائز على جوائز. حمام سباحة خاص وإطلالات بحرية.',
      location: 'Fouka Bay',
      area: 'North Coast',
      city: 'North Coast',
      pricePerNight: 4200,
      utilitiesEst: 0,
      cleaningFee: 800,
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 7,
      amenities: ['Private Pool', 'Beach Access', 'Gym', 'Parking', 'WiFi', 'AC', 'Kitchen', 'BBQ', 'Security', 'Concierge'],
      images: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&q=80',
      ],
      rating: 4.8,
      reviewCount: 29,
      refundPolicy: 'non-refundable',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 5 * 60 * 60 * 1000),
      viewCount: 255,
      latitude: 31.0100,
      longitude: 28.5600,
    },
    {
      slug: 'hacienda-bay-apartment',
      title: 'Stylish Apartment at Hacienda Bay',
      titleAr: 'شقة أنيقة في هاسيندا باي',
      description: 'Charming 2-bedroom apartment with garden views in the lush Hacienda Bay resort. Access to 3 pools, multiple beaches, sports facilities, and a vibrant dining scene.',
      descriptionAr: 'شقة جميلة من غرفتين مع إطلالات على الحديقة في منتجع هاسيندا باي الأخضر.',
      location: 'Hacienda Bay',
      area: 'North Coast',
      city: 'North Coast',
      pricePerNight: 2800,
      utilitiesEst: 0,
      cleaningFee: 500,
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      amenities: ['Pool', 'Beach Access', 'Sports Courts', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Restaurants', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
      ],
      rating: 4.7,
      reviewCount: 22,
      refundPolicy: 'moderate',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 8 * 60 * 60 * 1000),
      viewCount: 178,
      latitude: 30.9200,
      longitude: 28.6800,
    },
    {
      slug: 'el-gouna-lagoon-villa',
      title: 'Lagoon Villa in El Gouna',
      titleAr: 'فيلا بحيرة في الجونة',
      description: 'Stunning 3-bedroom villa with direct lagoon access and private dock in the enchanting El Gouna. Walk to restaurants, shops, and the famous Marina. Perfect year-round destination.',
      descriptionAr: 'فيلا مذهلة من 3 غرف نوم مع وصول مباشر للبحيرة ورصيف خاص في الجونة الساحرة.',
      location: 'Abu Tig Marina',
      area: 'El Gouna',
      city: 'El Gouna',
      pricePerNight: 4800,
      utilitiesEst: 200,
      cleaningFee: 900,
      bedrooms: 3,
      bathrooms: 3,
      maxGuests: 6,
      amenities: ['Private Dock', 'Lagoon Access', 'Pool', 'Parking', 'WiFi', 'AC', 'Kitchen', 'BBQ', 'Water Sports', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      ],
      rating: 4.9,
      reviewCount: 38,
      refundPolicy: 'moderate',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 4 * 60 * 60 * 1000),
      viewCount: 312,
      latitude: 27.3894,
      longitude: 33.6789,
    },
    {
      slug: 'gouna-downtown-apartment',
      title: 'Chic Apartment in El Gouna Downtown',
      titleAr: 'شقة أنيقة في وسط مدينة الجونة',
      description: 'Modern 2-bedroom apartment in the heart of El Gouna Downtown, steps from the best restaurants, boutiques, and the famous Kafr El Gouna strip. Perfect base for exploring this magical town.',
      descriptionAr: 'شقة عصرية من غرفتين في قلب وسط مدينة الجونة، على بعد خطوات من أفضل المطاعم والمتاجر.',
      location: 'Downtown El Gouna',
      area: 'El Gouna',
      city: 'El Gouna',
      pricePerNight: 2200,
      utilitiesEst: 150,
      cleaningFee: 400,
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      amenities: ['Pool', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Restaurants Nearby', 'Bike Rental', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      ],
      rating: 4.6,
      reviewCount: 19,
      refundPolicy: 'flexible',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 12 * 60 * 60 * 1000),
      viewCount: 134,
      latitude: 27.3950,
      longitude: 33.6820,
    },
    {
      slug: 'gouna-golf-villa',
      title: 'Golf Course Villa in El Gouna',
      titleAr: 'فيلا ملعب الغولف في الجونة',
      description: 'Magnificent 4-bedroom villa overlooking the 18-hole championship golf course in El Gouna. Private pool, lush gardens, and concierge service available.',
      descriptionAr: 'فيلا رائعة من 4 غرف نوم تطل على ملعب الغولف البطولي ذو 18 حفرة في الجونة.',
      location: 'Golf Course Area',
      area: 'El Gouna',
      city: 'El Gouna',
      pricePerNight: 6500,
      utilitiesEst: 350,
      cleaningFee: 1200,
      bedrooms: 4,
      bathrooms: 4,
      maxGuests: 8,
      amenities: ['Private Pool', 'Golf Access', 'Garden', 'Parking', 'WiFi', 'AC', 'Kitchen', 'BBQ', 'Concierge', 'Security'],
      images: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      ],
      rating: 5.0,
      reviewCount: 8,
      refundPolicy: 'non-refundable',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 48 * 60 * 60 * 1000),
      viewCount: 89,
      latitude: 27.3800,
      longitude: 33.6700,
    },
    {
      slug: 'sheikh-zayed-modern-villa',
      title: 'Contemporary Villa in Sheikh Zayed',
      titleAr: 'فيلا معاصرة في الشيخ زايد',
      description: 'Sleek 3-bedroom villa in the upscale Beverly Hills compound, Sheikh Zayed. Designer interiors, private pool, rooftop terrace with city views, and close proximity to Arkan Mall.',
      descriptionAr: 'فيلا أنيقة من 3 غرف نوم في كمبوند بيفرلي هيلز الراقي، الشيخ زايد.',
      location: 'Beverly Hills',
      area: 'Sheikh Zayed',
      city: 'Giza',
      pricePerNight: 3800,
      utilitiesEst: 280,
      cleaningFee: 650,
      bedrooms: 3,
      bathrooms: 3,
      maxGuests: 6,
      amenities: ['Private Pool', 'Rooftop', 'Gym', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Smart Home', 'Security', 'BBQ'],
      images: [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      ],
      rating: 4.7,
      reviewCount: 15,
      refundPolicy: 'moderate',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 7 * 60 * 60 * 1000),
      viewCount: 201,
      latitude: 30.0566,
      longitude: 30.9927,
    },
    {
      slug: 'zayed-park-apartment',
      title: 'Park-View Apartment in Zayed',
      titleAr: 'شقة بإطلالة على الحديقة في زايد',
      description: 'Lovely 2-bedroom apartment with serene park views in the heart of Sheikh Zayed. Modern furnishings, fully equipped kitchen, and convenient access to Hyper One and Mall of Arabia.',
      descriptionAr: 'شقة جميلة من غرفتين مع إطلالات هادئة على الحديقة في قلب الشيخ زايد.',
      location: 'Al Burouj',
      area: 'Sheikh Zayed',
      city: 'Giza',
      pricePerNight: 1600,
      utilitiesEst: 120,
      cleaningFee: 300,
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      amenities: ['Gym', 'Parking', 'WiFi', 'AC', 'Kitchen', 'Washer', 'Security', 'Smart TV', 'Workspace'],
      images: [
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      ],
      rating: 4.5,
      reviewCount: 21,
      refundPolicy: 'flexible',
      eligibility: 'all',
      isActive: true,
      lastBooked: new Date(Date.now() - 10 * 60 * 60 * 1000),
      viewCount: 156,
      latitude: 30.0700,
      longitude: 31.0100,
    },
  ]

  for (const listingData of listings) {
    const listing = await prisma.listing.create({ data: listingData })

    // Add 3 reviews per listing
    await prisma.review.createMany({
      data: [
        {
          listingId: listing.id,
          authorName: 'Sarah M.',
          authorCountry: 'UAE',
          rating: 5,
          comment: 'Absolutely fantastic stay! The property was exactly as described, impeccably clean, and the host was incredibly responsive. Would definitely book again!',
          source: 'BirdNest',
        },
        {
          listingId: listing.id,
          authorName: 'Ahmed K.',
          authorCountry: 'Egypt',
          rating: 4,
          comment: 'Great location and nice amenities. The apartment was well-furnished and comfortable. Check-in was smooth. Minor issue with WiFi speed but otherwise perfect.',
          source: 'BirdNest',
        },
        {
          listingId: listing.id,
          authorName: 'John D.',
          authorCountry: 'UK',
          rating: 5,
          comment: 'Exceptional value for money. The views are breathtaking and the property is maintained to a very high standard. Perfect for our family holiday.',
          source: 'BirdNest',
        },
      ],
    })
  }

  console.log('Seeding complete! Created', listings.length, 'listings with reviews.')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
