export type Listing = {
  id: string
  slug: string
  title: string
  titleAr: string
  description: string
  descriptionAr: string
  location: string
  area: string
  city: string
  pricePerNight: number
  utilitiesEst: number
  cleaningFee: number
  bedrooms: number
  bathrooms: number
  maxGuests: number
  amenities: string[]
  images: string[]
  rating: number
  reviewCount: number
  refundPolicy: string
  eligibility: string
  isActive: boolean
  lastBooked: Date | null
  viewCount: number
  latitude: number | null
  longitude: number | null
  createdAt: Date
  // --- Real data sourced from the official BirdNest unit sheet ---
  // Optional so existing demo/seed code stays valid. Used to surface real
  // specs and to seed the database later. See BIRDNEST_UNITS.md for the
  // fields still needing real values (price, location, photos).
  unitCode?: string
  view?: string
  sizeSqm?: number | null
  furnishCategory?: string | null
  bedConfigKing?: number
  bedConfigSingle?: number
  sourceUrl?: string
}

export type Review = {
  id: string
  listingId: string
  authorName: string
  authorCountry: string
  rating: number
  comment: string
  source: string
  createdAt: Date
}

// 19 real BirdNest units imported from the official sheet (2026-06-22).
// Specs (type, view, size, beds, baths, furnish, unit code) are REAL.
// pricePerNight, location/area/city, and images are PLACEHOLDERS pending the
// real data from birdnestlife.com / the photo drive — see BIRDNEST_UNITS.md.
export const mockListings: Listing[] = [
  {
    id: "5594",
    slug: "1-bedroom-apartment-5594",
    title: "1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة",
    description: "High-quality furnished 1-bedroom apartment of 90 m². Sleeps up to 2 guests across 1 king bed, with 1 bathroom. A verified BirdNest home (Unit 5594).",
    descriptionAr: "شقة مفروشة من غرفة واحدة  بمساحة 90 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5594.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80","https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5594",
    view: "No view",
    sizeSqm: 90,
    furnishCategory: "High Quality",
    bedConfigKing: 1,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5594",
  },
  {
    id: "5291",
    slug: "pool-view-1-bedroom-apartment-5291",
    title: "Pool-View 1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة بإطلالة على المسبح",
    description: "1-bedroom apartment of 80 m² with pool views. Sleeps up to 2 guests across 1 king bed, with 1 bathroom. A verified BirdNest home (Unit 5291).",
    descriptionAr: "شقة مفروشة من غرفة واحدة بإطلالة على المسبح بمساحة 80 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5291.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Pool"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5291",
    view: "Pool view",
    sizeSqm: 80,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5291",
  },
  {
    id: "5735",
    slug: "sea-view-2-bedroom-apartment-5735",
    title: "Sea-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على البحر",
    description: "BirdNest-furnished 2-bedroom apartment of 150 m² with sea views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5735).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على البحر بمساحة 150 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5735.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Sea View","Beach Access","Beachfront","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5735",
    view: "Sea",
    sizeSqm: 150,
    furnishCategory: "BirdNest Furnish",
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5735",
  },
  {
    id: "5287",
    slug: "canal-view-3-bedroom-apartment-5287",
    title: "Canal-View 3-Bedroom Apartment",
    titleAr: "شقة 3 غرف بإطلالة على القناة",
    description: "3-bedroom apartment of 165 m² with canal views. Sleeps up to 6 guests across 1 king bed and 4 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5287).",
    descriptionAr: "شقة مفروشة من 3 غرف بإطلالة على القناة بمساحة 165 متر مربع. تتسع حتى 6 ضيوف. وحدة موثقة من بيرد نست رقم 5287.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 4200,
    utilitiesEst: 150,
    cleaningFee: 650,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Canal View"],
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80","https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5287",
    view: "Canal view",
    sizeSqm: 165,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 4,
    sourceUrl: "https://birdnestlife.com/unit/5287",
  },
  {
    id: "5340",
    slug: "city-view-2-bedroom-apartment-5340",
    title: "City-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على المدينة",
    description: "2-bedroom apartment of 120 m² with city views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5340).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على المدينة بمساحة 120 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5340.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","City View"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5340",
    view: "City",
    sizeSqm: 120,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5340",
  },
  {
    id: "5744",
    slug: "canal-view-3-bedroom-apartment-5744",
    title: "Canal-View 3-Bedroom Apartment",
    titleAr: "شقة 3 غرف بإطلالة على القناة",
    description: "High-quality furnished 3-bedroom apartment of 218 m² with canal views. Sleeps up to 6 guests across 2 king beds and 2 single beds, with 3 bathrooms. A verified BirdNest home (Unit 5744).",
    descriptionAr: "شقة مفروشة من 3 غرف بإطلالة على القناة بمساحة 218 متر مربع. تتسع حتى 6 ضيوف. وحدة موثقة من بيرد نست رقم 5744.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 4200,
    utilitiesEst: 150,
    cleaningFee: 650,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Canal View","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80","https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5744",
    view: "Canal view",
    sizeSqm: 218,
    furnishCategory: "High Quality",
    bedConfigKing: 2,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5744",
  },
  {
    id: "5296",
    slug: "sea-view-2-bedroom-apartment-5296",
    title: "Sea-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على البحر",
    description: "2-bedroom apartment of 124 m² with sea views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5296).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على البحر بمساحة 124 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5296.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Sea View","Beach Access","Beachfront"],
    images: ["https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5296",
    view: "Sea view",
    sizeSqm: 124,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5296",
  },
  {
    id: "5589",
    slug: "pool-view-2-bedroom-apartment-5589",
    title: "Pool-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على المسبح",
    description: "High-quality furnished 2-bedroom apartment of 120 m² with pool views. Sleeps up to 4 guests across 4 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5589).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على المسبح بمساحة 120 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5589.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Pool","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5589",
    view: "Pool",
    sizeSqm: 120,
    furnishCategory: "High Quality",
    bedConfigKing: 0,
    bedConfigSingle: 4,
    sourceUrl: "https://birdnestlife.com/unit/5589",
  },
  {
    id: "5295",
    slug: "1-bedroom-apartment-5295",
    title: "1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة",
    description: "1-bedroom apartment. Sleeps up to 2 guests across 1 king bed, with 1 bathroom. A verified BirdNest home (Unit 5295).",
    descriptionAr: "شقة مفروشة من غرفة واحدة . تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5295.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80","https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5295",
    view: "No view",
    sizeSqm: null,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5295",
  },
  {
    id: "5673",
    slug: "1-bedroom-apartment-5673",
    title: "1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة",
    description: "1-bedroom apartment of 100 m². Sleeps up to 2 guests across 1 king bed, with 1 bathroom. A verified BirdNest home (Unit 5673).",
    descriptionAr: "شقة مفروشة من غرفة واحدة  بمساحة 100 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5673.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator"],
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80","https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5673",
    view: "No view",
    sizeSqm: 100,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5673",
  },
  {
    id: "5289",
    slug: "city-view-2-bedroom-apartment-5289",
    title: "City-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على المدينة",
    description: "2-bedroom apartment of 145 m² with city views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5289).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على المدينة بمساحة 145 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5289.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","City View"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5289",
    view: "City",
    sizeSqm: 145,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5289",
  },
  {
    id: "5671",
    slug: "golf-view-2-bedroom-apartment-5671",
    title: "Golf-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على ملعب الجولف",
    description: "2-bedroom apartment of 140 m² with golf course views. Sleeps up to 6 guests across 2 king beds and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5671).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على ملعب الجولف بمساحة 140 متر مربع. تتسع حتى 6 ضيوف. وحدة موثقة من بيرد نست رقم 5671.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Golf Access"],
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5671",
    view: "Golf",
    sizeSqm: 140,
    furnishCategory: "Standard",
    bedConfigKing: 2,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5671",
  },
  {
    id: "5595",
    slug: "canal-view-1-bedroom-apartment-5595",
    title: "Canal-View 1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة بإطلالة على القناة",
    description: "High-quality furnished 1-bedroom apartment of 102 m² with canal views. Sleeps up to 2 guests across 1 king bed, with 1 bathroom. A verified BirdNest home (Unit 5595).",
    descriptionAr: "شقة مفروشة من غرفة واحدة بإطلالة على القناة بمساحة 102 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5595.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Canal View","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80","https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5595",
    view: "Canal view",
    sizeSqm: 102,
    furnishCategory: "High Quality",
    bedConfigKing: 1,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5595",
  },
  {
    id: "5620",
    slug: "pool-view-3-bedroom-apartment-5620",
    title: "Pool-View 3-Bedroom Apartment",
    titleAr: "شقة 3 غرف بإطلالة على المسبح",
    description: "High-quality furnished 3-bedroom apartment of 150 m² with pool views. Sleeps up to 6 guests across 1 king bed and 4 single beds, with 2 bathrooms. Includes a separate nanny room. A verified BirdNest home (Unit 5620).",
    descriptionAr: "شقة مفروشة من 3 غرف بإطلالة على المسبح بمساحة 150 متر مربع. تتسع حتى 6 ضيوف. وحدة موثقة من بيرد نست رقم 5620.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 4200,
    utilitiesEst: 150,
    cleaningFee: 650,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Pool","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5620",
    view: "Pool view",
    sizeSqm: 150,
    furnishCategory: "High Quality",
    bedConfigKing: 1,
    bedConfigSingle: 4,
    sourceUrl: "https://birdnestlife.com/unit/5620",
  },
  {
    id: "5609",
    slug: "garden-view-2-bedroom-apartment-5609",
    title: "Garden-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على الحديقة",
    description: "2-bedroom apartment of 145 m² with garden views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5609).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على الحديقة بمساحة 145 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5609.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Garden"],
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5609",
    view: "Garden",
    sizeSqm: 145,
    furnishCategory: "Standard",
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5609",
  },
  {
    id: "5663",
    slug: "pool-view-2-bedroom-apartment-5663",
    title: "Pool-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على المسبح",
    description: "High-quality furnished 2-bedroom apartment with pool views. Sleeps up to 4 guests, with 2 bathrooms. A verified BirdNest home (Unit 5663).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على المسبح. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5663.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Pool","Premium Furnishing"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5663",
    view: "Pool",
    sizeSqm: null,
    furnishCategory: "High Quality",
    bedConfigKing: 0,
    bedConfigSingle: 0,
    sourceUrl: "https://birdnestlife.com/unit/5663",
  },
  {
    id: "5578",
    slug: "canal-view-1-bedroom-apartment-5578",
    title: "Canal-View 1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة بإطلالة على القناة",
    description: "1-bedroom apartment of 78 m² with canal views. Sleeps up to 2 guests across 2 single beds, with 1 bathroom. A verified BirdNest home (Unit 5578).",
    descriptionAr: "شقة مفروشة من غرفة واحدة بإطلالة على القناة بمساحة 78 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5578.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Canal View"],
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80","https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5578",
    view: "Canal view",
    sizeSqm: 78,
    furnishCategory: "Standard",
    bedConfigKing: 0,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5578",
  },
  {
    id: "5586",
    slug: "pool-view-1-bedroom-apartment-5586",
    title: "Pool-View 1-Bedroom Apartment",
    titleAr: "شقة غرفة واحدة بإطلالة على المسبح",
    description: "1-bedroom apartment of 106 m² with pool views. Sleeps up to 2 guests across 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5586).",
    descriptionAr: "شقة مفروشة من غرفة واحدة بإطلالة على المسبح بمساحة 106 متر مربع. تتسع حتى 2 ضيوف. وحدة موثقة من بيرد نست رقم 5586.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 1800,
    utilitiesEst: 150,
    cleaningFee: 300,
    bedrooms: 1,
    bathrooms: 2,
    maxGuests: 2,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Pool"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5586",
    view: "Pool",
    sizeSqm: 106,
    furnishCategory: "Standard",
    bedConfigKing: 0,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5586",
  },
  {
    id: "5714",
    slug: "sea-view-2-bedroom-apartment-5714",
    title: "Sea-View 2-Bedroom Apartment",
    titleAr: "شقة غرفتين بإطلالة على البحر",
    description: "2-bedroom apartment of 200 m² with sea views. Sleeps up to 4 guests across 1 king bed and 2 single beds, with 2 bathrooms. A verified BirdNest home (Unit 5714).",
    descriptionAr: "شقة مفروشة من غرفتين بإطلالة على البحر بمساحة 200 متر مربع. تتسع حتى 4 ضيوف. وحدة موثقة من بيرد نست رقم 5714.",
    location: "BirdNest Verified Home",
    area: "Egypt",
    city: "Egypt",
    pricePerNight: 2800,
    utilitiesEst: 150,
    cleaningFee: 450,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ["WiFi","AC","Kitchen","Washer","Smart TV","Security","Parking","Elevator","Sea View","Beach Access","Beachfront"],
    images: ["https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800&q=80","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80"],
    rating: 0,
    reviewCount: 0,
    refundPolicy: "flexible",
    eligibility: "all",
    isActive: true,
    lastBooked: null,
    viewCount: 0,
    latitude: null,
    longitude: null,
    createdAt: new Date('2026-06-22'),
    unitCode: "5714",
    view: "Sea",
    sizeSqm: 200,
    furnishCategory: null,
    bedConfigKing: 1,
    bedConfigSingle: 2,
    sourceUrl: "https://birdnestlife.com/unit/5714",
  }
]

// No reviews yet for the real units (ratings start at "New").
export const mockReviews: Review[] = []

export const destinations = [
  {
    id: 'new-cairo',
    name: 'New Cairo',
    nameAr: 'القاهرة الجديدة',
    description: 'Modern living in Cairo\'s most prestigious district',
    image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=600&q=80',
    propertyCount: 4,
    slug: 'new-cairo',
  },
  {
    id: 'north-coast',
    name: 'North Coast',
    nameAr: 'الساحل الشمالي',
    description: 'Mediterranean beaches and luxury resorts',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    propertyCount: 3,
    slug: 'north-coast',
  },
  {
    id: 'el-gouna',
    name: 'El Gouna',
    nameAr: 'الجونة',
    description: 'The Venice of the Red Sea',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80',
    propertyCount: 3,
    slug: 'el-gouna',
  },
  {
    id: 'sheikh-zayed',
    name: 'Sheikh Zayed',
    nameAr: 'الشيخ زايد',
    description: 'Upscale compounds and urban convenience',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    propertyCount: 2,
    slug: 'sheikh-zayed',
  },
]
